name: Test S3 Upload

on:
  workflow_dispatch:

permissions:
  actions: read
  id-token: write
  contents: read

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Download existing scraper artifact
        uses: actions/download-artifact@v5
        with:
          name: flipkart-mobile-assortment
          run-id: 35963928746
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: Check downloaded file
        run: |
          echo "Files downloaded:"
          find . -maxdepth 2 -type f -print

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_SCRAPER_DEPLOY_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Upload Excel to S3
        run: |
          FILE=$(find . -maxdepth 2 -type f -name "*.xlsx" | head -n 1)

          if [ -z "$FILE" ]; then
            echo "ERROR: No Excel file found."
            exit 1
          fi

          echo "Uploading: $FILE"

          aws s3 cp \
            "$FILE" \
            "s3://snapmint-scraper-739589793672-ap-south-1-an/fk_smartphone/"

          echo "S3 upload completed successfully."